### ISSUE TITLE
Only one little suggestion

### ISSUE THREAD

**Issue by eryfree** [NoEnv/vertx-cronutils#6]
First of all Thanks for your opensource project. 
I used in my project, when i use quartz cron express I realized that the quartz expression like “0 0/2 * * 11 ? 2023-2013” throw an IllegalArgumentException. I find source code in cron-utils package the year expression must within 1970-2099. 
cron-utils code :
`private static CronDefinition quartz() {
        return CronDefinitionBuilder.defineCron()
                .withSeconds().withValidRange(0, 59).and()
                .withMinutes().withValidRange(0, 59).and()
                .withHours().withValidRange(0, 23).and()
                .withDayOfMonth().withValidRange(1, 31).supportsL().supportsW().supportsLW().supportsQuestionMark().and()
                .withMonth().withValidRange(1, 12).and()
                .withDayOfWeek().withValidRange(1, 7).withMondayDoWValue(2).supportsHash().supportsL().supportsQuestionMark().and()
                .withYear().withValidRange(1970, 2099).withStrictRange().optional().and()
                .withCronValidation(CronConstraintsFactory.ensureEitherDayOfWeekOrDayOfMonth())
                .instance();
    }
`
But  the range can change to build the own CronDefinition. So I suggest 'CronScheduler' class can has more 'create' method so can define own CronDefinition or CronParser.

**Comment by zyclonite** [comment]
For the above you should get an `java.lang.IllegalArgumentException: Failed to parse cron expression. Invalid range! [2023,2013]` exception

did you mean `2023-3013` or `2023-2113` ?

I can expose the `CronDefinition` for the create method but it won't work as a generated object (e.g. rxjava) as this would need to be modelled and mapped.

**Comment by zyclonite** [comment]
see https://github.com/NoEnv/vertx-cronutils/commit/80b0c8c3d31d25e8790adca09b0fdbceabf6a248 if this helps?

**Comment by eryfree** [comment]
> see [6d1dcf4](https://github.com/NoEnv/vertx-cronutils/commit/6d1dcf46ecb86ac3f087b87ebc7be860f9dd7ce5) if this helps?
Yes, thats what I mean , it really helps me.
